[buildPlans.jetka]
family = "Jetka"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false
no-ligation = true

[buildPlans.jetka.variants]
inherits = "ss20"

[buildPlans.jetka.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-i = "short-serifed"
capital-q = "straight"
g = "single-storey-flat-hook-serifless"
l = "tailed-serifed"
eszet = "longs-s-lig-descending"
cyrl-capital-ze = "bilateral-serifed"
one = "no-base"
four = "closed"
six = "closed-contour"
seven = "curly-serifless"
nine = "closed-contour"
paren = "normal"
ampersand = "upper-open"
at = "short"
question = "corner-flat-hooked"

[buildPlans.jetka.variants.italic]
h = "tailed"

[buildPlans.jetka.widths.normal]
shape = 500
menu = 5
css = "normal"
